### ISSUE TITLE
Y.append(ciao.index(classe)) gives error

### ISSUE THREAD

**Issue by ahorvath** [IcarPA-TBlab/MetagenomicDC#1]
Dear Developers,

I tried to run CNN.py with the provided example Fasta file 1000seq.fasta but it gave this error:

> Y.append(ciao.index(classe))
> 
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "./models/CNN.py", line 84, in <module>
>     X,Y,nb_classes,input_length = load_data(sys.argv[1])
>   File "./models/CNN.py", line 36, in load_data
>     Y.append(ciao.index(classe))
> NameError: global name 'ciao' is not defined

Can you please provide an example on how to use the classifier?

Many thanks for your help.

Bests,
Attila

**Comment by marcelocamacho** [comment]
I’m also dealing with the same problem.

**Comment by chaibenl** [comment]
I installed ciao (v. 0.1.0), but it does not have have the 'index' method. What is the behavior expected from this method?

**Comment by Sadiki-Noureddine** [comment]
Try with classes  [ Y.append(classes.index(classe)) ]

> Dear Developers,
> 
> I tried to run CNN.py with the provided example Fasta file 1000seq.fasta but it gave this error:
> 
> > Y.append(ciao.index(classe))
> > Using TensorFlow backend.
> > Traceback (most recent call last):
> > File "./models/CNN.py", line 84, in 
> > X,Y,nb_classes,input_length = load_data(sys.argv[1])
> > File "./models/CNN.py", line 36, in load_data
> > Y.append(ciao.index(classe))
> > NameError: global name 'ciao' is not defined
> 
> Can you please provide an example on how to use the classifier?
> 
> Many thanks for your help.
> 
> Bests,
> Attila
